# Generated by Django 5.1.4 on 2024-12-21 18:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_actor_director_genre_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='moviesseries',
            name='actors',
            field=models.ManyToManyField(to='main.actor'),
        ),
        migrations.AddField(
            model_name='moviesseries',
            name='director',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.director'),
        ),
        migrations.AddField(
            model_name='moviesseries',
            name='genres',
            field=models.ManyToManyField(to='main.genre'),
        ),
    ]
