# Generated by Django 5.1.4 on 2024-12-21 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_watchlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='actor',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='actors/'),
        ),
        migrations.AddField(
            model_name='moviesseries',
            name='popularity',
            field=models.IntegerField(default=0),
        ),
    ]
