# Generated by Django 5.1.4 on 2024-12-21 20:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_subscription_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='actor',
            name='moviesseries',
            field=models.ManyToManyField(related_name='actor_movies', to='main.moviesseries'),
        ),
        migrations.AddField(
            model_name='genre',
            name='movies',
            field=models.ManyToManyField(related_name='genre_movies', to='main.moviesseries'),
        ),
        migrations.AlterField(
            model_name='moviesseries',
            name='actors',
            field=models.ManyToManyField(related_name='related_actors', to='main.actor'),
        ),
        migrations.AlterField(
            model_name='moviesseries',
            name='director',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='directed_movies', to='main.director'),
        ),
        migrations.AlterField(
            model_name='moviesseries',
            name='genres',
            field=models.ManyToManyField(related_name='related_genres', to='main.genre'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to=settings.AUTH_USER_MODEL),
        ),
    ]
