# Generated by Django 5.1.4 on 2024-12-22 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_actor_awards_director_nationality_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='actor',
            name='poster',
            field=models.ImageField(blank=True, null=True, upload_to='posters/'),
        ),
    ]
