# Generated by Django 5.1.4 on 2024-12-22 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_actor_poster'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actor',
            name='poster',
        ),
    ]
