# Generated by Django 5.1.4 on 2024-12-22 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_subscription_is_active_alter_subscription_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='moviesseries',
            name='download_link',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
