# Generated by Django 5.1.4 on 2025-01-23 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_moviesseries_download_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='moviesseries',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
